apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-prod

resources:
  - ../../base
  - secret-sales-service-prod.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-configmap.yaml
