apiVersion: v1
kind: Service
metadata:
  name: sales-service
  labels:
    app.kubernetes.io/name: sales-service
    app.kubernetes.io/part-of: retail-microservices-platform
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: sales-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
