namespace: retail-dev

resources:
  - ../../base
  - namespace.yaml
  - hpa-sales-service.yaml
  - ingress-sales-service.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-configmap.yaml
  - secret-sales-service-dev.yaml
  - service.yaml
  - patch-service-loadbalancer.yaml
