apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-dev

resources:
  - ../../base
  - namespace.yaml
  - hpa-sales-service.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-configmap.yaml
  - secret-sales-service-dev.yaml
  - service.yaml
