apiVersion: v1
kind: Service
metadata:
  name: sales-service        # MUST match the base service name
spec:
  type: LoadBalancer         # override from ClusterIP -> LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
