apiVersion: v1
kind: Service
metadata:
  name: sales-service
  labels:
    app: sales-service
spec:
  type: ClusterIP   # base is internal only
  selector:
    app: sales-service
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
