apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-staging

resources:
  - ../../base
  - secret-sales-service-staging.yaml

patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-configmap.yaml
